version: '3'

services:
  confluence:
    image: atlassian/confluence-server
    ports:
      - "8090:8090"
    volumes:
      - ./confluence:/var/atlassian/application-data/confluence
    environment:
      - JVM_MINIMUM_MEMORY=1024m
      - JVM_MAXIMUM_MEMORY=2048m
      - JVM_SUPPORT_RECOMMENDED_ARGS=-Djdk.tls.client.protocols=TLSv1.2
